### ISSUE TITLE
Latest revision of qiskit-terra fails with the latest revision of rustworkx: No module named 'retworkx'

### ISSUE THREAD

**Issue by yurivict** [Qiskit/rustworkx#656]
### Information

- **retworkx version**: e9edfdc
- **Python version**: 3.9
- **Rust version**: 1.62.1
- **Operating system**: FreeBSD 13.1

### What is the current behavior?
The latest revision of [qiskit-terra](https://github.com/Qiskit/qiskit-terra) project fails with:
```
$ python3.9 x.py 
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/science/py-qiskit-terra/x.py", line 1, in <module>
    from qiskit import QuantumCircuit, transpile
  File "/usr/local/lib/python3.9/site-packages/qiskit/__init__.py", line 49, in <module>
    from qiskit.circuit import ClassicalRegister
  File "/usr/local/lib/python3.9/site-packages/qiskit/circuit/__init__.py", line 243, in <module>
    from .equivalence import EquivalenceLibrary
  File "/usr/local/lib/python3.9/site-packages/qiskit/circuit/equivalence.py", line 18, in <module>
    import retworkx as rx
ModuleNotFoundError: No module named 'retworkx'
```

### What is the expected behavior?
n/a

### Steps to reproduce the problem
Run a test program from ```qiskit-terra``` README.

The list of files installed by ```rustworks``` is:
```
$ pkg info -l py39-rustworkx 
py39-rustworkx-0.11.0.51:
	/usr/local/lib/python3.9/site-packages/rustworkx-0.12.0-py3.9.egg-info/PKG-INFO
	/usr/local/lib/python3.9/site-packages/rustworkx-0.12.0-py3.9.egg-info/SOURCES.txt
	/usr/local/lib/python3.9/site-packages/rustworkx-0.12.0-py3.9.egg-info/dependency_links.txt
	/usr/local/lib/python3.9/site-packages/rustworkx-0.12.0-py3.9.egg-info/not-zip-safe
	/usr/local/lib/python3.9/site-packages/rustworkx-0.12.0-py3.9.egg-info/requires.txt
	/usr/local/lib/python3.9/site-packages/rustworkx-0.12.0-py3.9.egg-info/top_level.txt
	/usr/local/lib/python3.9/site-packages/rustworkx/__init__.py
	/usr/local/lib/python3.9/site-packages/rustworkx/__pycache__/__init__.cpython-39.opt-1.pyc
	/usr/local/lib/python3.9/site-packages/rustworkx/__pycache__/__init__.cpython-39.pyc
	/usr/local/lib/python3.9/site-packages/rustworkx/__pycache__/visit.cpython-39.opt-1.pyc
	/usr/local/lib/python3.9/site-packages/rustworkx/__pycache__/visit.cpython-39.pyc
	/usr/local/lib/python3.9/site-packages/rustworkx/rustworkx.cpython-39.so
	/usr/local/lib/python3.9/site-packages/rustworkx/visit.py
	/usr/local/lib/python3.9/site-packages/rustworkx/visualization/__init__.py
	/usr/local/lib/python3.9/site-packages/rustworkx/visualization/__pycache__/__init__.cpython-39.opt-1.pyc
	/usr/local/lib/python3.9/site-packages/rustworkx/visualization/__pycache__/__init__.cpython-39.pyc
	/usr/local/lib/python3.9/site-packages/rustworkx/visualization/__pycache__/graphviz.cpython-39.opt-1.pyc
	/usr/local/lib/python3.9/site-packages/rustworkx/visualization/__pycache__/graphviz.cpython-39.pyc
	/usr/local/lib/python3.9/site-packages/rustworkx/visualization/__pycache__/matplotlib.cpython-39.opt-1.pyc
	/usr/local/lib/python3.9/site-packages/rustworkx/visualization/__pycache__/matplotlib.cpython-39.pyc
	/usr/local/lib/python3.9/site-packages/rustworkx/visualization/graphviz.py
	/usr/local/lib/python3.9/site-packages/rustworkx/visualization/matplotlib.py
	/usr/local/share/licenses/py39-rustworkx-0.11.0.51/APACHE20
	/usr/local/share/licenses/py39-rustworkx-0.11.0.51/LICENSE
	/usr/local/share/licenses/py39-rustworkx-0.11.0.51/catalog.mk
```

```retworkx``` isn't in it.

**Comment by yurivict** [comment]
I was missing the ```retworkx``` shim.

Sorry about the noise.
