### ISSUE TITLE
The 'Installing rustworkx' section of README doesn't explain how to run tests

### ISSUE THREAD

**Issue by yurivict** [Qiskit/rustworkx#695]
README should explain how to run tests after Rustworkx is built/installed from sources.

### Information

- **rustworkx version**: 0.12.0
- **Python version**: 3.9
- **Rust version**: 1.63.0
- **Operating system**: FreeBSD 13.1

**Comment by mtreinish** [comment]
How to run tests is documented in the contributing guide: https://github.com/Qiskit/rustworkx/blob/main/CONTRIBUTING.md#tests

**Comment by yurivict** [comment]
```tox -epy``` fails:
```
===>   py39-rustworkx-0.12.0 depends on file: /usr/local/bin/python3.9 - found
cd /disk-samsung/freebsd-ports/math/py-rustworkx/work-py39/rustworkx-0.12.0 && /usr/bin/env CARGO_HOME=/disk-samsung/freebsd-ports/math/py-rustworkx/work-py39/cargo-home  CARGO_BUILD_JOBS=6  CARGO_BUILD_TARGET=x86_64-unknown-freebsd  CARGO_TARGET_DIR=/disk-samsung/freebsd-ports/math/py-rustworkx/work-py39/rustworkx-0.12.0/target  CARGO_TARGET_X86_64_UNKNOWN_FREEBSD_LINKER="cc"  RUSTC=/usr/local/bin/rustc  RUSTDOC=/usr/local/bin/rustdoc  RUSTFLAGS=" -C link-arg=-fstack-protector-strong" RUST_BACKTRACE=1 XDG_DATA_HOME=/disk-samsung/freebsd-ports/math/py-rustworkx/work-py39  XDG_CONFIG_HOME=/disk-samsung/freebsd-ports/math/py-rustworkx/work-py39  XDG_CACHE_HOME=/disk-samsung/freebsd-ports/math/py-rustworkx/work-py39/.cache  HOME=/disk-samsung/freebsd-ports/math/py-rustworkx/work-py39 TMPDIR="/disk-samsung/freebsd-ports/math/py-rustworkx/work-py39" PATH=/usr/local/libexec/ccache:/disk-samsung/freebsd-ports/math/py-rustworkx/work-py39/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin PKG_CONFIG_LIBDIR=/disk-samsung/freebsd-ports/math/py-rustworkx/work-py39/.pkgconfig:/usr/local/libdata/pkgconfig:/usr/local/share/pkgconfig:/usr/libdata/pkgconfig NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES LDSHARED="cc -shared" PYTHONDONTWRITEBYTECODE= PYTHONOPTIMIZE= PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS="-fno-omit-frame-pointer"  LDFLAGS=" -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  MANPREFIX="/usr/local" CCACHE_DIR="/tmp/.ccache" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" tox -epy
/disk-samsung/freebsd-ports/math/py-rustworkx/work-py39/rustworkx-0.12.0/.tox/.package/lib/python3.9/site-packages/setuptools/build_meta.py:307: SetuptoolsDeprecationWarning: 
            The arguments ['--formats=gztar'] were given via `--global-option`.
            Please use `--build-option` instead,
            `--global-option` is reserved to flags like `--verbose` or `--quiet`.
            
  warnings.warn(msg, SetuptoolsDeprecationWarning)
py inst-nodeps: /disk-samsung/freebsd-ports/math/py-rustworkx/work-py39/rustworkx-0.12.0/.tox/.tmp/package/1/rustworkx-0.12.0.tar.gz
py installed: attrs==22.1.0,autopage==0.5.1,cliff==4.0.0,cmd2==2.4.2,extras==1.0.0,fixtures==4.0.1,future==0.18.2,importlib-metadata==5.0.0,networkx==2.8.7,pbr==5.10.0,prettytable==3.4.1,pyperclip==1.8.2,python-subunit==1.4.0,PyYAML==6.0,rustworkx==0.12.0,semantic-version==2.10.0,setuptools-rust==1.5.2,sqlite3==0.0.0,stestr==4.0.1,stevedore==4.0.0,testtools==2.5.0,typing-extensions==4.4.0,voluptuous==0.13.1,wcwidth==0.2.5,zipp==3.9.0
py run-test-pre: PYTHONHASHSEED='649497103'
py run-test: commands[0] | stestr run

=========================
Failures during discovery
=========================
--- import errors ---
Failed to import test module: rustworkx_tests.digraph.test_adjacency_matrix
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/disk-samsung/freebsd-ports/math/py-rustworkx/work-py39/rustworkx-0.12.0/tests/rustworkx_tests/digraph/test_adjacency_matrix.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

Failed to import test module: rustworkx_tests.digraph.test_dist_matrix
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/disk-samsung/freebsd-ports/math/py-rustworkx/work-py39/rustworkx-0.12.0/tests/rustworkx_tests/digraph/test_dist_matrix.py", line 15, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

Failed to import test module: rustworkx_tests.digraph.test_floyd_warshall
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/disk-samsung/freebsd-ports/math/py-rustworkx/work-py39/rustworkx-0.12.0/tests/rustworkx_tests/digraph/test_floyd_warshall.py", line 15, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'

Failed to import test module: rustworkx_tests.graph.test_adjencency_matrix
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/disk-samsung/freebsd-ports/math/py-rustworkx/work-py39/rustworkx-0.12.0/tests/rustworkx_tests/graph/test_adjencency_matrix.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

I think it fails to install numpy into the virtual environment.
